prettyPrint: true
cacheTTL: 0
openAPI:
  openapi: 3.0.1
  info:
    title: API of the Urban Tree species in Boulder, Colorado.
    description: 'This API uses the data provided by the City of Boulder about their Urban Tree Species.
      You can find all kind of information about the different Trees. Like their Leafcycle, Water Need, Dimensions, Species and Genus.'
    version: '1.0'
    contact:
      name: David Dadon
      email: david@dadon.fr
    license:
      name: Apache 2.0
      url: http://www.apache.org/licenses/LICENSE-2.0.html
  servers:
    -
      url: /api
      description: Production Server
